# discord-vc-bot configuration

prefix = "-"
debug = false # env: LYDIAN_DEBUG
# debug: Enables various commands and features intended for developers. See the
#    README for a full description of what debug mode does:
#    https://github.com/svioletg/lydian/blob/main/README.md
check_for_updates = true # env: LYDIAN_CHECK_UPDATES
# check_for_updates: Whether to check for new releases of Lydian at startup.
check_for_stable_only = true # env: LYDIAN_CHECK_STABLE_ONLY
# check_for_stable_only: Whether to exclude pre-releases when checking for
#    updates.
bot_console = true # env: LYDIAN_BOT_CONSOLE
# bot_console: Enables Lydian's interactive console while running.
max_duration = 'n/a'
# max_duration: Maximum duration (in seconds) of media that can be played by the
#    bot. Set to 'n/a' for no limit.
max_duration_allow_unknown = false
# max_duration_allow_unknown: Whether to allow media whose duration couldn't be
#    retrieved when max-duration is more than 0.
max_filesize = 20000000
# max_filesize: Maximum filesize in bytes for media that can be downloaded by
#    the bot. Will have no effect when streaming media (stream-media = true).
max_playlist_length = 20
# max_playlist_length: Maximum number of items that can be added from a single
#    playlist link.
max_queue_length = 100
# max_queue_length: Maximum number of items that can be added to the media
#    queue.
media_dir_warn_threshold = 100000000
# media_dir_warn_threshold: Total size in bytes that downloaded media can take
#    up before a warning is emitted at bot startup. Set to 'n/a' to disable the
#    warning entirely.
stream_media = true
# stream_media: Whether to stream media instead of downloading it to disk and
#    playing the file.
inactivity_timeout = 120
# inactivity_timeout: How long in seconds the bot can be inactive (not playing
#    anything and the queue is empty) before disconnecting. Set to 'n/a' to
#    never disconnect for inactivity.
lonely_timeout = 120
# lonely_timeout: How long in seconds the bot can be the only user in a voice
#    channel before disconnecting. Set to 'n/a' to never disconnect in this
#    case.

[command_aliases]
help = ["h"]
join = ["j"]
leave = ["l"]

[media_filter]
allowed_extractors = ['default']
# allowed_extractors: A list of regular expressions which determine what yt-dlp
#    extractors to allow. "default" will include almost every extractor yt-dlp
#    has available. Prefix an expression with a hyphen (-) to blacklist it
#    instead.
#    Extractor names: https://github.com/yt-dlp/yt-
#    dlp/blob/master/supportedsites.md
allowed_urls = ['https://.*']
# allowed_urls: A list of regular expressions which determine what URLs to
#    allow. Prefix an expression with a hyphen (-) to blacklist it instead.

[vote_skipping]
enabled = true
threshold_type = "percentage"
percentage = 50
exact = 3

[logging]
level = 20 # env: LYDIAN_LOG_LEVEL
# level: Minimum "level" of logs to show in terminal output. In ascending order,
#    one of: "TRACE",  "DEBUG",  "INFO",  "WARNING",  "ERROR".
#    Can also be their corresponding integer levels: 5, 10, 20, 30, 40
utc = true # env: LYDIAN_LOG_UTC
# utc: Whether to show log timestamps in UTC. If false, they are shown in your
#    system's local time.
