# discord-vc-bot configuration

prefix = "-"
# debug: Enables various commands and features intended for developers. Will
# also override the log level to "DEBUG".
debug = false # env: LYDIAN_DEBUG
max-filesize = 20000000

[vote-skipping]
enabled = true
threshold-type = "percentage"
percentage = 50
exact = 3

[logging]
log-level = "INFO"
# utc: Whether to show log timestamps in UTC. If false, they are shown in your
# system's local time.
utc = true # env: LYDIAN_LOG_UTC
